name: Prison
main: tech.mcprison.prison.spigot.SpigotPrison
version: "${version}"
description: Prison is an all-in-one plugin for the Minecraft prison game mode.
website: https://prison.jar-mc.com
softdepend: [Essentials, Vault, LuckPerms, Multiverse-Core, Multiworld, MVdWPlaceholderAPI, PlaceholderAPI, GemsEconomy, TokenEnchant, CMI]

# Older versions than 1.13 will ignore this, but this will allow 1.13 and up to use newer block types?
api-version: 1.13

  # ======================================================
  # New commands compatible only with spigot
  # ======================================================

permissions:

  # ==================
  # Core permissions
  # ==================

  prison.modules:
    description: Access to the /prison modules command.

  prison.convert:
    description: Access to the /prison convert command.

  prison.alerts:
    description: Access to the /prison alerts command, and the ability to be notified for new alerts.

  prison.alerts.clear:
    description: Clear your alerts.

  prison.alerts.clear.all:
    description: Clear the alerts for the entire server.
    
  prison.gui:
    description: Opens the Prison's GUI menu.

  prison.prisonmanagergui:
    description: Opens the Prison's GUI menu.

  prison.placeholder:
    description: Tools to list and test placeholders.

  # Permission Kits
  prison.admin:
    description: Administrative access to Prison's functionality.
    default: op
    children:
      prison.modules: true
      prison.convert: true
      prison.alerts: true
      prison.alerts.clear: true
      prison.alerts.clear.all: true
      prison.gui: true
      prison.prisonmanagergui: true
      prison.placeholder: true

  # ==================
  # Mines permissions
  # ==================

  mines.create:
    description: Access to the /mines create command.

  mines.rename:
    description: Access to the /mines rename command.
  
  mines.set:
    description: Access to the /mines set command.

  mines.block:
    description: Access to the /mines block command.

  mines.delete:
    description: Access to the /mines delete command.

  mines.info:
    description: Access to the /mines info command.

  mines.reset:
    description: Access to the /mines reset command.

  mines.wand:
    description: Access to the /mines wand command.

  mines.list:
    description: Access to the /mines list command.

  mines.skipreset:
    description: Access to the /mines set skipReset command.

  mines.zeroblockresetdelay:
    description: Access to the /mines set zeroBlockResetDelay command.

  mines.stats:
    description: Access to the /mines stats command.

  mines.whereami:
    description: Access to the /mines whereami command.
    
  mines.resettime:
    description: Access to the /mines set resetTime command.

  mines.notification:
    description: Access to the /mines set notification command.
    
  mines.tp:
    description: Access to the /mines tp command.

  mines.command:
    description: Access to the /mines command command.

  mines.admin:
    description: Contains all the commands for managing mines.
    default: op
    children:
      mines.block: true
      mines.create: true
      mines.rename: true
      mines.delete: true
      mines.set: true
      mines.info: true
      mines.wand: true
      mines.list: true
      mines.reset: true
      mines.skipreset: true
      mines.zeroblockresetdelay: true
      mines.stats: true
      mines.whereami: true
      mines.resettime: true
      mines.notification: true
      mines.tp: true
      mines.command: true

  # ==================
  # Ranks permissions
  # ==================

  ranks.user:
    description: Allows users to see the ranks and rank up.
    default: true

  ranks.command:
    description: Access to the /ranks command command.

  ranks.ladder:
    description: Access to the /ranks ladder command.

  ranks.info:
    description: Access to the /ranks info command.

  ranks.list:
    description: Access to the /ranks list command.

  ranks.create:
    description: Access to the /ranks create command.

  ranks.delete:
    description: Access to the /ranks delete command.

  ranks.promote:
    description: Access to the /ranks promote command.

  ranks.demote:
    description: Access to the /ranks demote command.

  ranks.setrank:
    description: Access to the /ranks set rank command.

  
  ranks.admin:
    description: Contains all the commands reserved for admins.
    default: op
    children:
      ranks.user: true
      ranks.command: true
      ranks.ladder: true
      ranks.info: true
      ranks.list: true
      ranks.create: true
      ranks.delete: true
      ranks.promote: true
      ranks.demote: true
      ranks.setrank: true
